/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5446329a-83f2-414f-b13e-ab00743f3403",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_cWebMJ22b",
    "aws_user_pools_web_client_id": "5ip9q18kaud9qhvigtg67l1a56",
    "oauth": {}
};


export default awsmobile;
